# Generated by Django 3.1.7 on 2021-11-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211112_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creator',
        ),
    ]
