# Generated by Django 3.1.7 on 2021-11-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20211113_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='followee',
            field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.PROTECT, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
