# Generated by Django 3.1.7 on 2021-11-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20211116_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
