# Generated by Django 3.1.7 on 2021-11-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
