# Generated by Django 3.1.7 on 2021-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_counter',
            field=models.IntegerField(default=0, max_length=56),
        ),
    ]
