# Generated by Django 3.1.7 on 2021-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_post_likes_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_counter',
            field=models.IntegerField(default=0),
        ),
    ]
